services:
    queues:
        class: SerendipityHQ\Bundle\QueuesBundle\Service\QueuesManager
        arguments: ["@queues.do_not_use.entity_manager"]
#This service is meant to be privately used by QueuesRunCommand
    queues.do_not_use.daemon:
        class: SerendipityHQ\Bundle\QueuesBundle\Service\QueuesDaemon
        arguments: ["@queues.do_not_use.entity_manager"]
