services:
    queues:
        class: SerendipityHQ\Bundle\CommandsQueuesBundle\Service\QueuesManager
        arguments: ["@commands_queues.do_not_use.entity_manager"]
#This service is meant to be privately used by QueuesRunCommand
    commands_queues.do_not_use.daemon:
        class: SerendipityHQ\Bundle\CommandsQueuesBundle\Service\QueuesDaemon
        arguments: ["@commands_queues.do_not_use.entity_manager"]
