# Template here
# https://symfony.com/doc/current/bundles/best_practices.html#continuous-integration
language: php

os:
    - linux

matrix:
    fast_finish: true
    include:
        # Test the latest stable release building coverage and performing all checks
        -   php: '7.3'
            env: FULL_CHECK=true
        -   php: '7.2'
            env: FULL_CHECK=true
        -   php: '7.1'
            env: FULL_CHECK=true

        # Minimum supported dependencies with the latest and oldest PHP version
        -   php: '7.3'
            env: FULL_CHECK=true COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"
        -   php: '7.2'
            env: FULL_CHECK=true COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"
        -   php: '7.1'
            env: FULL_CHECK=true COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="weak_vendors"

before_install:
    - if [[ $FULL_CHECK == true ]]; then pecl channel-update pecl.php.net; fi;
    - if [[ $FULL_CHECK == true ]]; then pecl install ast-0.1.6; fi;

install:
    - composer update ${COMPOSER_FLAGS} --prefer-dist --prefer-stable
    - cat vendor/thecodingmachine/safe/rector-migrate.yml

script:
    - if [[ $FULL_CHECK == true ]]; then bin/validate; fi
