language: php

matrix:
    include:
        - php: 7.0
        - php: 7.1

cache:
    directories:
        - $HOME/.composer/cache

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml
    - phpenv config-rm xdebug.ini || return 0

after_script:
  - CODECLIMATE_REPO_TOKEN="43a95c87684011727ab09e4c5f838c39a7815a82e2405eeae42b1602fea90dcc" vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

addons:
  code_climate:
    repo_token: 43a95c87684011727ab09e4c5f838c39a7815a82e2405eeae42b1602fea90dcc
