SerendipityHQ\Bundle\QueuesBundle\Entity\Job:
    type: entity
    table: queues_scheduled_jobs
    repositoryClass: SerendipityHQ\Bundle\QueuesBundle\Repository\JobRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        command:
            type: string
            nullable: false
        arguments:
            type: array
            nullable: false
        createdAt:
            column: created_at
            type: datetime
            nullable: false
        startedAt:
            column: started_at
            type: datetime
            nullable: true
        closedAt:
            column: closed_at
            type: datetime
            nullable: true
        executeAfterTime:
            column: execute_after_time
            type: datetime
            nullable: true
        debug:
            column: debug
            type: array
            nullable: true
        priority:
            type: smallint
            nullable: false
        queue:
            type: string
            nullable: false
        status:
            type: string
            nullable: false
        output:
            type: text
            nullable: true
        exitCode:
            type: integer
            nullable: true
    manyToOne:
        processedBy:
            targetEntity: SerendipityHQ\Bundle\QueuesBundle\Entity\Daemon
            inversedBy: jobs
            joinColumn:
                name: processedBy
                referencedColumnName: id
    manyToMany:
        parentDependencies:
            targetEntity: SerendipityHQ\Bundle\QueuesBundle\Entity\Job
            inversedBy: childDependencies
            joinTable:
                name: queues_jobs_chains
                joinColumns:
                    child_job:
                        referencedColumnName: id
                inverseJoinColumns:
                    parent_job:
                        referencedColumnName: id
        childDependencies:
            targetEntity: SerendipityHQ\Bundle\QueuesBundle\Entity\Job
            mappedBy: parentDependencies

