SerendipityHQ\Bundle\QueuesBundle\Model\ScheduledJob:
    type: entity
    table: queues_scheduled_jobs
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        command:
            type: string
            nullable: false
        arguments:
            type: array
            nullable: false
        priority:
            type: smallint
            nullable: false
        queue:
            type: string
            nullable: false
