SerendipityHQ\Bundle\QueuesBundle\Model\ScheduledJob:
    type: entity
    table: queues_scheduled_jobs
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        command:
            type: string
            nullable: false
        arguments:
            type: array
            nullable: false
        priority:
            type: smallint
            nullable: false
        queue:
            type: string
            nullable: false
        status:
            type: string
            nullable: false
        createdAt:
            name: created_at
            type: datetime
            nullable: false
        startedAt:
            name: started_at
            type: datetime
            nullable: true
        closedAt:
            name: closed_at
            type: datetime
            nullable: true
