services:
    queues:
        class: SerendipityHQ\Bundle\CommandsQueuesBundle\Service\QueuesManager
        arguments: ["@shq_commands_queues.do_not_use.entity_manager"]
    Doctrine\ORM\EntityManagerInterface $doNotUseEntityManager: "@shq_commands_queues.do_not_use.entity_manager"
    SerendipityHQ\Bundle\CommandsQueuesBundle\Util\JobsMarker $doNotUseJobsMarker: "@shq_commands_queues.do_not_use.jobs_marker"
