name: PHP CS Fixer

on: [ push, pull_request ]

jobs:
    phpcs:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                php: [ '7.4' ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none # disable xdebug, pcov
                    extensions: ast, json, pcntl

            -   name: Find Composer's cache directory
                uses: ./.github/actions/composer/find-cache-dir

            -   name: Cache Composer's dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ env.COMPOSER_CACHE_DIR }}
                    key: php-composer-dependencies-cache

            -   name: Install Composer deps
                run: |
                    composer update --no-interaction

            -   name: Run PHP CS Fixer
                run: |
                    ./vendor/bin/php-cs-fixer fix --allow-risky yes --dry-run -v
