name: PHPStan

on: [push, pull_request]

jobs:
    serendipity_hq:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: ['7.3', '7.4', '8.0']
                symfony: ['~4.4', '~5.2']
                composer-flags: ['--prefer-stable --prefer-lowest', '']
        name: PHP ${{ matrix.php }} SF ${{ matrix.symfony }} (${{ matrix.composer-flags }}) on ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@2.9.0
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none # disable xdebug, pcov
                  extensions: ast, json, pcntl

            - name: Fix Symfony version
              run: |
                  composer req symfony/flex --no-scripts
                  composer config extra.symfony.require "${{ matrix.symfony }}"

            - name: Remove Rector
              run: |
                  composer rem rector/rector --dev

            - name: Install Composer deps
              run: |
                  composer update ${{ matrix.composer-flags }} --no-interaction --no-suggest --no-scripts

            - name: Run PHPStan
              run: |
                  ./vendor/bin/phpstan analyse --no-progress -c phpstan.ci-with-baseline.neon
