name: Rector

on: [push, pull_request]

jobs:
    serendipity_hq:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: ['7.2']
        env:
            COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        name: PHP ${{ matrix.php }} on ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none # disable xdebug, pcov
                  tools: prestissimo, pecl
                  extensions: ast, intl

            - name: Install Composer deps
              run: |
                  composer update --no-interaction --no-suggest

            - name: Run Rector
              run: |
                  ./vendor/bin/rector process src --dry-run
                  ./vendor/bin/rector process tests --dry-run
